import { Link } from "@tanstack/react-router";
import { ArrowRight, CalendarDays, Camera, Check, HeartHandshake, Monitor, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { PageIntro } from "@/components/shared";
import hero from "@/assets/topsmiles-hero.jpg";
import portrait from "@/assets/topsmiles-portrait.jpg";
import clinic from "@/assets/topsmiles-clinic.jpg";
import { services } from "@/lib/mock-api";

export const faqs = [
  ["What happens after I submit?", "Your booking request and any payment proof are reviewed. You will receive the next status update through the contact details you provide."],
  ["Is the consultation fee the treatment price?", "No. A consultation fee covers the consultation itself. A deposit is clearly labelled and is not presented as the full treatment price."],
  ["Is uploading a payment screenshot confirmation?", "No. A screenshot places the payment under review. Your appointment is confirmed only after the payment is verified."],
  ["What photos should I prepare?", "Clear photos in natural light: a relaxed front smile, a close front view, and one side view. The booking form guides you through them."],
];
export function HomePage() { return <>
  <section className="relative min-h-[calc(100svh-5rem)] overflow-hidden">
    <img src={hero} width={1600} height={1104} alt="Patient smiling in a contemporary dental studio" className="absolute inset-0 h-full w-full object-cover object-[62%_center]"/>
    <div className="absolute inset-0 bg-[linear-gradient(90deg,var(--color-background)_0%,color-mix(in_oklab,var(--color-background)_88%,transparent)_38%,color-mix(in_oklab,var(--color-background)_20%,transparent)_78%)]"/>
    <div className="relative mx-auto flex min-h-[calc(100svh-5rem)] max-w-7xl items-center px-5 py-16 lg:px-8"><div className="max-w-2xl"><p className="eyebrow">Considered cosmetic dentistry</p><h1 className="mt-5 font-display text-6xl leading-[.95] sm:text-7xl lg:text-8xl">Your smile,<br/><span className="text-primary">thoughtfully</span><br/>considered.</h1><p className="mt-7 max-w-lg text-base leading-7 text-foreground/75 sm:text-lg">Begin with a focused consultation designed to understand your goals, review your photos, and make the next step clear.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="xl"><Link to="/book">Book a consultation <ArrowRight/></Link></Button><Button asChild variant="outline" size="xl"><Link to="/services">Explore services</Link></Button></div></div></div>
    <div className="absolute bottom-0 right-0 hidden w-80 border-l border-t border-border bg-background/85 p-6 backdrop-blur md:block"><p className="text-xs uppercase text-muted-foreground">Start online</p><p className="mt-2 font-display text-2xl">A guided consultation in five clear steps.</p></div>
  </section>
  <section className="section-pad px-5 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">Consultations</p><h2 className="mt-3 max-w-xl font-display text-4xl sm:text-5xl">A clear first step, whichever way you prefer to meet.</h2></div><Button asChild variant="link"><Link to="/services">View all services <ArrowRight/></Link></Button></div><div className="mt-14 grid gap-px bg-border lg:grid-cols-3">{services.map((s, i) => <article key={s.id} className="bg-background p-7 transition-colors hover:bg-surface"><span className="text-xs text-primary">0{i+1}</span><h3 className="mt-10 font-display text-3xl">{s.name}</h3><p className="mt-4 min-h-20 text-sm leading-6 text-muted-foreground">{s.description}</p><div className="mt-8 flex justify-between border-t border-border pt-5 text-xs"><span>{s.duration} min · {s.format}</span><span>{s.fee ? `${s.paymentLabel} $${s.fee}` : "No payment required"}</span></div></article>)}</div></div></section>
  <section className="bg-surface section-pad px-5 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_1.1fr] lg:items-center"><img src={portrait} loading="lazy" width={1008} height={1264} alt="A natural smile in a dental consultation setting" className="aspect-[4/5] w-full object-cover"/><div className="lg:pl-12"><p className="eyebrow">How it works</p><h2 className="mt-4 font-display text-5xl">From curiosity to a considered plan.</h2><div className="mt-10 space-y-8">{[[CalendarDays,"Choose your consultation","Select the service, date, and time that fit your needs."],[Camera,"Tell us about your smile","Share your goals and optional guided dental photos."],[HeartHandshake,"Receive clear next steps","Your submission is reviewed before any appointment is confirmed."]].map(([Icon,t,c],i)=><div key={String(t)} className="grid grid-cols-[3rem_1fr] gap-5"><div className="flex size-11 items-center justify-center rounded-full border border-primary/40 text-primary"><Icon/></div><div><p className="text-xs text-primary">0{i+1}</p><h3 className="mt-1 text-lg font-semibold">{String(t)}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{String(c)}</p></div></div>)}</div><Button asChild className="mt-10" size="lg"><Link to="/book">Start your consultation <ArrowRight/></Link></Button></div></div></section>
  <section className="section-pad px-5 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">The clinic</p><h2 className="mt-4 font-display text-5xl">A calm, modern setting for considered care.</h2><p className="mt-6 max-w-xl leading-7 text-muted-foreground">TopSmilesNova is presented here as a premium cosmetic dental consultation concept. Clinic credentials, address, team details, and opening hours remain editable until verified business information is supplied.</p><Button asChild variant="outline" className="mt-8"><Link to="/about">About the clinic</Link></Button></div><img src={clinic} loading="lazy" width={1408} height={1008} alt="Contemporary dental consultation room" className="aspect-[7/5] w-full object-cover"/></div></section>
  <section id="gallery" className="bg-surface section-pad px-5 lg:px-8"><div className="mx-auto max-w-7xl"><p className="eyebrow">Visual journal</p><div className="mt-6 grid gap-4 md:grid-cols-[1.3fr_.7fr]"><img src={hero} loading="lazy" width={1600} height={1104} alt="Natural smile portrait" className="h-[28rem] w-full object-cover"/><img src={portrait} loading="lazy" width={1008} height={1264} alt="Smile consultation portrait" className="h-[28rem] w-full object-cover"/></div><p className="mt-4 text-xs text-muted-foreground">Editorial demo imagery. No treatment outcome is implied.</p></div></section>
  <section id="faqs" className="section-pad px-5 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Questions</p><h2 className="mt-4 font-display text-5xl">Before you book.</h2></div><Accordion type="single" collapsible>{faqs.map(([q,a],i)=><AccordionItem value={`item-${i}`} key={q}><AccordionTrigger className="text-left text-base">{q}</AccordionTrigger><AccordionContent className="max-w-2xl leading-6 text-muted-foreground">{a}</AccordionContent></Accordion>)}</div></section>
  <section className="border-y border-border bg-primary px-5 py-16 text-primary-foreground lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-7 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase">Ready when you are</p><h2 className="mt-2 font-display text-4xl">Start with a thoughtful conversation.</h2></div><Button asChild variant="secondary" size="xl"><Link to="/book">Book a consultation <ArrowRight/></Link></Button></div></section>
</>; }

export function ContentPage({ type }: { type: "services"|"gallery"|"about"|"contact"|"policies" }) { const content = {
 services: ["Consultations & services", "Choose the right place to begin.", "Every option is clearly labelled with its format, duration, and whether the amount shown is a consultation fee, a deposit, or free."],
 gallery: ["Gallery", "A closer look at the TopSmilesNova atmosphere.", "Editorial demo imagery illustrates the intended brand direction and does not represent treatment outcomes."],
 about: ["About", "Modern dentistry, with room to listen.", "This demo communicates a careful, consultation-led approach. Verified clinician biographies, accreditations, and clinic details can be added when supplied."],
 contact: ["Contact", "Let’s begin the conversation.", "Use the editable contact placeholders below or start the guided consultation when you are ready."],
 policies: ["Booking policies", "Clear expectations from the start.", "These are editable demo policies and should be reviewed by the clinic before publication."],
 }[type];
 return <div className="px-5 lg:px-8"><section className="section-pad mx-auto max-w-7xl"><PageIntro eyebrow={content[0]} title={content[1]} copy={content[2]}/>{type === "services" && <div className="mt-14 grid gap-5 md:grid-cols-3">{services.map(s=><article key={s.id} className="border border-border bg-surface p-6"><Sparkles className="text-primary"/><h2 className="mt-8 font-display text-3xl">{s.name}</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">{s.description}</p><dl className="mt-8 space-y-3 border-t border-border pt-5 text-sm"><div className="flex justify-between"><dt>Duration</dt><dd>{s.duration} minutes</dd></div><div className="flex justify-between"><dt>Format</dt><dd>{s.format}</dd></div><div className="flex justify-between"><dt>{s.paymentLabel}</dt><dd>{s.fee ? `$${s.fee} ${s.currency}` : "No charge"}</dd></div></dl><Button asChild className="mt-7 w-full"><Link to="/book">Select consultation</Link></Button></article>)}</div>}
 {type === "gallery" && <div className="mt-14 grid gap-4 md:grid-cols-2"><img src={hero} alt="Smile portrait" className="aspect-[4/3] w-full object-cover"/><img src={clinic} alt="Clinic interior" className="aspect-[4/3] w-full object-cover"/><img src={portrait} alt="Consultation portrait" className="aspect-[4/3] w-full object-cover md:col-span-2"/></div>}
 {type === "about" && <div className="mt-14 grid gap-10 lg:grid-cols-2"><img src={clinic} alt="Clinic consultation room" className="w-full object-cover"/><div className="space-y-6 text-muted-foreground"><p>TopSmilesNova is designed around unhurried consultation, transparent booking steps, and a refined patient experience.</p><p>The clinical team, credentials, formal affiliations, address, and opening hours shown in the final website should use verified clinic information only.</p><div className="grid gap-3 border-t border-border pt-6 text-sm text-foreground">{["Consultation-led approach","Clear fee and deposit labels","Manual payment review before confirmation"].map(x=><p key={x} className="flex gap-3"><Check className="text-primary"/> {x}</p>)}</div></div></div>}
 {type === "contact" && <div className="mt-14 grid gap-px bg-border md:grid-cols-3">{[["Clinic address","[Add verified clinic address]"],["Telephone","[Add clinic phone number]"],["Opening hours","[Add verified opening hours]"]].map(([a,b])=><div className="bg-surface p-7" key={a}><p className="eyebrow">{a}</p><p className="mt-5 text-lg">{b}</p></div>)}</div>}
 {type === "policies" && <div className="mt-14 max-w-3xl space-y-8">{[["Requests and confirmation","Submitting the form creates a booking request. An appointment is confirmed only when its status changes to Confirmed."],["Fees and deposits","Any consultation fee or deposit is displayed before submission. A deposit is not the full treatment price."],["Manual payments","Payment proof is reviewed manually. An uploaded screenshot is not confirmation that funds were received."],["Changes and cancellations","Add the clinic’s verified rescheduling, cancellation, refund, and late-arrival terms here before publication."],["Photos and information","Submitted information and photos should be handled according to the clinic’s verified privacy policy."]].map(([h,p],i)=><section key={h} className="border-t border-border pt-6"><p className="text-xs text-primary">0{i+1}</p><h2 className="mt-2 font-display text-3xl">{h}</h2><p className="mt-3 leading-7 text-muted-foreground">{p}</p></section>)}</div>}
 </section></div>; }
